apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: insta
  template:
    metadata:
      labels:
        app: insta
    spec:
      containers:
        - name: insta
          image: yash5090/insta:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
